### ISSUE TITLE
No email going to admin

### ISSUE THREAD

**Issue by mysmartmedia** [BrilliantPlugins/salesforce-wordpress-to-lead#45]
No copy of the lead email in the admin email account.

After lots of testing and search for someone else who may have already solved this... not sure what I am missing - I get a copy of it in the "leads" email acct but not the "admins" email account when testing.

Everything appears to be properly importing into SF... hopefully this is an appropriate question to ask in this platform... its probably simple but after many tries in the last hour to repair this... I need someone else's brain on this.

Thanks!

**Comment by nciske** [comment]
Are other emails from WordPress arriving to the admin email account?

Are your MX records setup to correctly route mail to the domain used by the admin email account (e.g. external mail server, but the web server thinks it's the mail server?

Do you have spam filtering on that account?
