### ISSUE TITLE
Street field not working

### ISSUE THREAD

**Issue by johnsonphoto** [BrilliantPlugins/salesforce-wordpress-to-lead#47]
Hello,
Great plugin. I'm just having one issue. I create the form in salesforce then import it. In salesforce I add the field "street" as a text field to be included in the form. If I make it a required field it just won't let the form be sent and keeps saying it must be filled out. If it's an unrequited field it will let the form send but will not populate the address field. 

If I just add the salesforce generated html code onto a page the "Street" field works just fine. 

Thanks in advance.

**Comment by nciske** [comment]
Why is the street field not in the import?

I can't duplicate the issue on my end - adding a `street` field works as expected. Can you show me how you have the field setup?

**Comment by johnsonphoto** [comment]
Hi Nick,
Here's the code I was using. It's just strait from the SF Web-to-lead form generator. I was importing it just as is. I've take the SF id out but that's it. Thanks for your time. 







<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=UTF-8">





<form action="https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST">

<input type=hidden name="oid" value="">
<input type=hidden name="retURL" value="http://www.jaaronwoodcountertops.com/thank-you-dealer-page/">









<label for="first_name">First Name</label><input  id="first_name" maxlength="40" name="first_name" size="20" type="text" /><br>

<label for="last_name">Last Name</label><input  id="last_name" maxlength="80" name="last_name" size="20" type="text" /><br>

<label for="email">Email</label><input  id="email" maxlength="80" name="email" size="20" type="text" /><br>

<label for="company">Company</label><input  id="company" maxlength="40" name="company" size="20" type="text" /><br>

<label for="city">City</label><input  id="city" maxlength="40" name="city" size="20" type="text" /><br>

<label for="state">State/Province</label><input  id="state" maxlength="20" name="state" size="20" type="text" /><br>

<label for="title">Title</label><input  id="title" maxlength="40" name="title" size="20" type="text" /><br>

<label for="URL">Website</label><input  id="URL" maxlength="80" name="URL" size="20" type="text" /><br>

<label for="phone">Phone</label><input  id="phone" maxlength="40" name="phone" size="20" type="text" /><br>

<label for="fax">Fax</label><input  id="fax" maxlength="40" name="fax" size="20" type="text" /><br>

<label for="street">Street</label><textarea name="street"></textarea><br>

<label for="zip">Zip</label><input  id="zip" maxlength="20" name="zip" size="20" type="text" /><br>

<label for="country">Country</label><input  id="country" maxlength="40" name="country" size="20" type="text" /><br>

How Did You Hear About Us?:<select  id="00NE0000002BJkO" name="00NE0000002BJkO" title="How Did You Hear About Us?"><option value="">--None--</option><option value="Referred By A Friend or Family Member">Referred By A Friend or Family Member</option>
<option value="Referred By A Local Dealer">Referred By A Local Dealer</option>
<option value="Referred By A J. Aaron Sales Rep">Referred By A J. Aaron Sales Rep</option>
<option value="Google">Google</option>
<option value="Bing">Bing</option>
<option value="Yahoo">Yahoo</option>
<option value="General Web Lead">General Web Lead</option>
<option value="Stone Design">Stone Design</option>
<option value="Todl.com">Todl.com</option>
<option value="CadDetails.com">CadDetails.com</option>
<option value="KBIS/Trade Show">KBIS/Trade Show</option>
<option value="Ad">Ad</option>
<option value="Cold Call">Cold Call</option>
<option value="Print Ad">Print Ad</option>
<option value="PR">PR</option>
<option value="Other">Other</option>
</select><br>

Do you have samples?:<select  id="00NE0000005lgec" name="00NE0000005lgec" title="Do you have samples?"><option value="">--None--</option><option value="Yes">Yes</option>
<option value="No">No</option>
<option value="We have another brand&#39;s samples">We have another brand&#39;s samples</option>
</select><br>

Do you have a display?:<select  id="00NE0000005lgeh" name="00NE0000005lgeh" title="Do you have a display?"><option value="">--None--</option><option value="Yes">Yes</option>
<option value="No">No</option>
<option value="Yes, but not from J. Aaron or EnGRAIN">Yes, but not from J. Aaron or EnGRAIN</option>
</select><br>

Are You A::<select  id="00NE0000005lkEd" name="00NE0000005lkEd" title="Are You A:"><option value="">--None--</option><option value="Kitchen &amp; Bath Showroom">Kitchen &amp; Bath Showroom</option>
<option value="Residential Designer">Residential Designer</option>
<option value="Commercial Designer">Commercial Designer</option>
<option value="Residential Architect">Residential Architect</option>
<option value="Commercial Architect">Commercial Architect</option>
<option value="Cabinet Shop">Cabinet Shop</option>
<option value="Countertop Fabrication Shop">Countertop Fabrication Shop</option>
<option value="Home Builder/Remodeler">Home Builder/Remodeler</option>
<option value="Design Build Firm">Design Build Firm</option>
<option value="Homeowner">Homeowner</option>
</select><br>

Main Source Of Income:<select  id="00NE0000005lkEs" multiple="multiple" name="00NE0000005lkEs" title="Main Source Of Income"><option value="Cabinets">Cabinets</option>
<option value="Hardware">Hardware</option>
<option value="Lighting">Lighting</option>
<option value="Plumbing">Plumbing</option>
<option value="Tile">Tile</option>
<option value="Stone/Other Countertops">Stone/Other Countertops</option>
<option value="Design Services">Design Services</option>
</select><br>

<input type="submit" name="submit">

</form>

**Comment by nciske** [comment]
OK, I tested mine as a textarea and it still works as expected... so that's not it.

Can you show me screenshot of the street field as generated by the import (or as added by you)?

Just to verify: you only have 1 `street` field on your form -- you said "In salesforce I add the field "street" as a text field to be included in the form." -- why would you need to add a street field -- you should already have one?

**Comment by johnsonphoto** [comment]
Well that's strange. I deleted the form that had the original issue and now the import won't include the street field. No idea why. It was including it using the import tool, just not allowing it to populate. 

When I said I was adding the street field I just meant that I was moving it over to the selected fields from the available fields options when creating the form. I was using the street field that came with SF. 

Attached is a screen shot of what I'm starting with in SF
![screen](https://cloud.githubusercontent.com/assets/17591241/13480847/c1913e52-e0ae-11e5-898e-09dd0b8a526d.png)
