### ISSUE TITLE
Cannot use the "title" field for a Lead in a form - causes 404

### ISSUE THREAD

**Issue by isleshocky77** [BrilliantPlugins/salesforce-wordpress-to-lead#50]
Currently there is no way to have a field named "title" in the lead object filled out using this plugin.  The issue is that all fields are created a field with name being the name of the Salesforce field.  When you attempt to use the Salesforce System field "title" then a new form field with name "title" is inputted in the wordpress form. This then gets intercepted before for the action and Wordpress attempts to search for posts with a title of the value of the title field.

I've looked through the code surrounding the problem in wp/wp-includes/query.php to try and find a way of having some other way to tell wordpress to not attempt to look by title; however, I was unable to find anything that could help.

I would say the proper way to do this would probably be to prefix all the fields with something specific to the plugin when creating the form and then remove the prefix before sending the data to salesforce in site/web/app/plugins/salesforce-wordpress-to-lead/salesforce.php

Others have reported this problem on the Support forum at https://wordpress.org/support/topic/form-submission-fails-with-a-404

**Comment by isleshocky77** [comment]
Just a note, I decided to go look through PRs and the Fork network and found you were working on another branch of the plugin. It looks like you've already done the suggestion in this issue in 4c098eb4c9dd863d25cef5e74dd9afe500a149ed

**Comment by nciske** [comment]
Yes, this is fixed in the v3.x branch -- should be out this month. Thanks for the report.

**Comment by nciske** [comment]
v3 has not been released yet. All WP reserved names are now auto-prefixed as of [v2.3.7.5](https://github.com/BrilliantPlugins/salesforce-wordpress-to-lead/releases/tag/v2.7.3.5)
