### ISSUE TITLE
Incorrect form class: Labels align top 

### ISSUE THREAD

**Issue by indiecitizen** [BrilliantPlugins/salesforce-wordpress-to-lead#62]
Using development version of plugin: 3.0.1.1 (upgraded from 2.x on Oct. 13, 2016 to fix a different problem)
When I use legacy form number, labels align to left of field.
[salesforce form=”4″]
When I use new form number, labels align on top of field.
[salesforce_form id=”15180″]

Both are on this page: https://voicesforciviljustice.org/for-advocates-2/sign-up-new/
Legacy is above. New is below. Both shortcodes refer to the exact same form, on which which label location=left aligned.

Custom CSS is the default newly copied from the Styling tab today. I can’t think what else to change. Thank you.
****
When I posted the above on Wordpress.org, Nick replied that it may be bug, and requested I repost this here.  Thank you.

**Comment by nciske** [comment]
This should be fixed in [v3.0.1.3](https://github.com/BrilliantPlugins/salesforce-wordpress-to-lead/releases/tag/v3.0.1.3)
