### ISSUE TITLE
Plugin sending emails to the wrong (or unspecified) email address.

### ISSUE THREAD

**Issue by WraithActual** [BrilliantPlugins/salesforce-wordpress-to-lead#65]
When a new request/message is sent via our contact form, the plugin seems to send a confirmation email to admin@companyname.com, although we have never set that email, and have asked the plugin to send emails to enquiries@companyname.com.

Any ideas?  I've scoured the plugin settings, and our wordpress settings, but i cant see the admin@ email address anywhere.

Many thanks

Tom

**Comment by nciske** [comment]
The plugin sends email to the WP admin email if _Send blog admin an email notification_ is checked. 

If you specify additional emails in the _Email new submissions to_ setting it will CC them as well.

You can also filter that list so it may be in the code -- see `salesforce_w2l_cc_admin_email_list` on this page for more info:
https://wordpress.org/plugins/salesforce-wordpress-to-lead/other_notes/

If it's not in any of those locations... something else is altering the email outside this plugin.
