### ISSUE TITLE
Saleforce support given me a email

### ISSUE THREAD

**Issue by GautamKarma** [BrilliantPlugins/salesforce-wordpress-to-lead#71]
Hi Support,

I need your help on my website I have used your plugin where any user fill that form all data been stored on salesforce lead account. But yesterday I get an email from salesforce where they mention like this can you please help me on this.

Email:

Salesforce could not create this lead because of the reason listed below. For more information about this error or help with Web-to-Case-Lead, please contact Customer Support.

Reason: You’re creating a duplicate record. We recommend you use an existing record instead.
Lead Capture Page: https://webto.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8

Record Information:

email = navyofficer1227@yahoo.com

encoding = UTF-8
encoding = UTF-8
lead_source = Lead form on aspire
oid = 00D410000012WHp
orgid = 00D410000012WHp

To incorporate this lead into salesforce.com you can key in the data above.

If you have any questions, please click on Support at the top right of any page within salesforce.com.

Customer Support
salesforce.com

Thanks
Gautam

**Comment by nciske** [comment]
Support is handled via the WordPress.org support forum.       
  
  
  
  
  

  
  
>

**Comment by GautamKarma** [comment]
But on that no one been response
