### ISSUE TITLE
PHP7 Compatibility

### ISSUE THREAD

**Issue by stodorovic** [BrilliantPlugins/salesforce-wordpress-to-lead#76]
It's related to https://wordpress.org/support/topic/compatibility-with-php-7-0-3/

I see that it isn't fixed in last release and I made PR #75 I hope that you will fix it in next release.

**Comment by nciske** [comment]
Merged back un June.

**Comment by stodorovic** [comment]
Current version of plugin ( 2.7.3.2 ) doesn't contain this PR. Please update plugin on wordpress.org. It's again reported - https://wordpress.org/support/topic/release-with-php-7-0-upgrade-anytime-soon/
