### ISSUE TITLE
Redirect to File Download Causes Continual Page Load 

### ISSUE THREAD

**Issue by mrobinsonquivers** [BrilliantPlugins/salesforce-wordpress-to-lead#77]
Firstly, I LOVE the functionality of salesforce-to-wordpress-to-lead. It does exactly what we need to it to do! The only issue we have is we are utilizing this lead for as a way to allow users to download case study content. Once they populate the form and submit, they are rewarded with an automatic file download. The issue is, we are utilizing the form redirect URL as the download trigger for the file. My guess is the download triggers but the action is expecting a new location so it spins out. Is there any way that the reaction if by downloaded file can just stay on the page where the form exists?

**Comment by markjohnnightingale** [comment]
Chère cliente, cher client, 

Je pars en congés pendant quelques jours (du jeudi 5 juillet au mardi 11 juillet inclus), avec un accès restreint à ma boîte mail. 

Je prendrai connaissance de votre demande le mercredi 12 juillet 2017.

Bon weekend, 

Mark Nightingale

**Comment by nciske** [comment]
I have not tested file downloads in the thank you URL, but as it's just a document.location JS call, it should work with a file URL.

Is there a URL I can see the issue in action on?

**Comment by mrobinsonquivers** [comment]
Yes, most certainly!

https://blog.quivers.com/go/case-studies/

Marissa Robinson
Director of Professional Services
Marissa@Quivers.com<mailto:Marissa@Quivers.com>
+1.909.273.4238

www.Quivers.com<http://www.quivers.com/>



On Jul 11, 2017, at 1:44 PM, Nick Ciske <notifications@github.com<mailto:notifications@github.com>> wrote:


I have not tested file downloads in the thank you URL, but as it's just a document.location JS call, it should work with a file URL.

Is there a URL I can see the issue in action on?

**Comment by nciske** [comment]
So, the gist is... the plugin is doing what you asked it to: redirect them to the file URL.

I assume you're wanting them not to be on a blank page after download?

Are you opposed to creating a thank you page with a link to the download instead? That would work with the plugin without any modifications.

I can look at adding a URL/File toggle that changes the behavior to something less jarring using one of these techniques:
https://stackoverflow.com/questions/1066452/easiest-way-to-open-a-download-window-without-navigating-away-from-the-page

But I can’t guarantee when I'll get to it.

**Comment by mrobinsonquivers** [comment]
Hi Nick!

Yes thank you for such a quick review. You are correct, we are trying to avoid the blank page. We can’t do the thank you page because then there is nothing stopping someone from sharing that URL and us missing out on that lead all together.

I hope that makes sense! Let me know your thoughts and thank you for the reactivity.

Marissa Robinson
Director of Professional Services
Marissa@Quivers.com<mailto:Marissa@Quivers.com>
+1.909.273.4238

www.Quivers.com<http://www.quivers.com/>



On Jul 11, 2017, at 1:58 PM, Nick Ciske <notifications@github.com<mailto:notifications@github.com>> wrote:


So, the gist is... the plugin is doing what you asked it to: redirect them to the file URL.

I assume you're wanting them not to be on a blank page after download?

Are you opposed to creating a thank you page with a link to the download instead? That would work with the plugin without any modifications.

I can look at adding a URL/File toggle that changes the behavior to something less jarring using one of these techniques:
https://stackoverflow.com/questions/1066452/easiest-way-to-open-a-download-window-without-navigating-away-from-the-page

But I can’t guarantee when I'll get to it.

**Comment by mrobinsonquivers** [comment]
Another note, sales@quivers.com<mailto:sales@quivers.com> is not being notified of the sales submissions it appears. Salesforce portion is perfect!

Marissa Robinson
Director of Professional Services
Marissa@Quivers.com<mailto:Marissa@Quivers.com>
+1.909.273.4238

www.Quivers.com<http://www.quivers.com/>



On Jul 11, 2017, at 1:58 PM, Nick Ciske <notifications@github.com<mailto:notifications@github.com>> wrote:


So, the gist is... the plugin is doing what you asked it to: redirect them to the file URL.

I assume you're wanting them not to be on a blank page after download?

Are you opposed to creating a thank you page with a link to the download instead? That would work with the plugin without any modifications.

I can look at adding a URL/File toggle that changes the behavior to something less jarring using one of these techniques:
https://stackoverflow.com/questions/1066452/easiest-way-to-open-a-download-window-without-navigating-away-from-the-page

But I can’t guarantee when I'll get to it.

**Comment by nciske** [comment]
Marissa,

Please open a separate issue for your email deliverability concern (if you want assistance with that). Thanks!
