### ISSUE TITLE
Can not map to custom fields in SFDC

### ISSUE THREAD

**Issue by mrobinsonquivers** [BrilliantPlugins/salesforce-wordpress-to-lead#78]
Currently, there is a way to add fields on the forms, but not a way to map those custom fields into SalesForce. Is this by design or is something missing to connect?

**Comment by nciske** [comment]
Just put the custom field API name (e.g. CustomField__c) in the "new" field name and it'll get written to that field in Salesforce upon submit.

There are several FAQs in the readme on proper custom field usage -- Salesforce makes it harder than it should be... but that's life in Salesforce-land.
https://wordpress.org/plugins/salesforce-wordpress-to-lead/#faq

**Comment by mrobinsonquivers** [comment]
Salesforce knows how to make it complicated don’t they! Appreciate the information and how quickly you always reach out, Nick. Have a good one!

Marissa Robinson
Director of Professional Services
Marissa@Quivers.com<mailto:Marissa@Quivers.com>
+1.909.273.4238

www.Quivers.com<http://www.quivers.com/>



On Jul 12, 2017, at 3:10 PM, Nick Ciske <notifications@github.com<mailto:notifications@github.com>> wrote:


Just put the custom field API name (e.g. CustomField__c) in the "new" field name and it'll get written to that field in Salesforce upon submit.

There are several FAQs in the readme on proper custom field usage -- Salesforce makes it harder than it should be... but that's life in Salesforce-land.
https://wordpress.org/plugins/salesforce-wordpress-to-lead/#faq
