### ISSUE TITLE
Form is not working

### ISSUE THREAD

**Issue by suzietawney** [BrilliantPlugins/salesforce-wordpress-to-lead#79]
https://www.openlending.com/allied-lead-form

It loads but when you hit submit, nothing happens.

**Comment by nciske** [comment]
Please read the **FAQ** regarding proper use of field names (aka API Names, yours are invalid for HTML use, and won't map to Salesforce properly -- you need to use the machine name, not the human friendly label).

Hint: if it has spaces, punctuation, etc. it's not the right thing.

`Account Name` - not a valid field name
`Allied Sales Rep Name` - not a valid field name
`Estimated Date of Meeting` - not a valid field name

https://wordpress.org/plugins/salesforce-wordpress-to-lead/#faq

**Specifically this Q/A:**
What are the built in field names? Not all the fields are working when I use the Field Label in the lead edit screen?

**And this one:**
How do I use a SalesForce custom field?
