### ISSUE TITLE
Hello i have issue in submitting the form

### ISSUE THREAD

**Issue by hiteshcms** [BrilliantPlugins/salesforce-wordpress-to-lead#81]
Hello,

When we submit the lead generation contact form it saw the following error "Failed to connect to Salesforce.com."
This is our site url  "http://sandiegocrm.com/contact/"
And i also have checked with the enabling WordPress Debug mode but still can not find any proper error.
So please help up us to working the form correctly and we can get lead into our Salesforce crm.

Thanks
Hitesh Mandli

**Comment by GrimsGramS** [comment]
Hello,
used the correct companyID from Salesforce (setup->companysetup->companyinformation?
And Web-to-Lead enables in Salesforce setup-settings?

For the php-errors at submitting and preferences check the other issue, there are fixed files.

Greets

**Comment by nciske** [comment]
This is almost always an issue with your server not supporting the SSL/TLS requirements Salesforce implemented recently.

There's more information in the WP.org support forum:
https://wordpress.org/support/topic/readme-new-endpoints-and-tls-upgrades/
