### ISSUE TITLE
Connection to Salesofrce.com error

### ISSUE THREAD

**Issue by Dominich7** [BrilliantPlugins/salesforce-wordpress-to-lead#82]
Hi there,

Our IT  support have moved our site to cloudflare and now web to lead forms aren't working.  The website is https://www.nlgcommercial.nz/ is there's anything that needs to be done our end?

Thanks
Dominic

**Comment by nciske** [comment]
Worked for for me.

FYI- The support forum is over on WordPress.org.

Please use issues for bug reports/pull requests. 

Thanks.

**Comment by Dominich7** [comment]
Hello Nciske,
Our  web to lead forms aren't working again. https://www.nlgcommercial.nz/quote-request/ I'm getting a 'failed to connect to salesforce.com error' again.

Thanks
Dominic

**Comment by Dominich7** [comment]
No worries our hosting guy found something with dns settings, all working now

Thanks anyway 
Dominic
