### ISSUE TITLE
Error message on "Success" page after form submission

### ISSUE THREAD

**Issue by Lynda1952** [BrilliantPlugins/salesforce-wordpress-to-lead#84]
I recently installed the plugin on a client's WordPress site. They've been using SalesForce for years, and on their old site (before my time), they had a "leads" page where their staff or board members could input baic lead info for Salesforce, that would be followed up later.

Our Salesforce support guy suggested we install the plugin and re-create the leads page, which I did, at http://www.createnow.org/leads, then ran a test. Everything went well - the lead went into Salesforce, the acknowledgement email went to the WP admin's email address, and the Success page loaded. But on that page, above the word "Success!!", was the following error message:

Notice: Undefined variable: form_type in /home/hx57i3f4f0a1/public_html/wp-content/plugins/salesforce-wordpress-to-lead/salesforce.php on line 805

Is this something I can correct in the PHP code, or a bug on Brilliant's end? I'm an old-school HTML/CSS coder who can get around okay in WordPress and edit PHP with guidance, but I have no idea how this Git thing works! Hope someone with newbie patience can give me a hand here. :)

**Comment by GrimsGramS** [comment]
Hey,
same Problem here. I fixed it for me. I think there has been a refactoring of some functions and setting some default values (form_type, layout and donotautoaddcolontolabels).

@Lynda1952 
I attached the two changed files.

CHANGES (salesforce.php):
- function **salesforce_cc_admin** -> _added form_type parameter_

CHANGES (lib/salesforce_admin.class.php):
- **isset-check for layout** ($options['forms'][$form_id]['layout'], 833)
- **isset-check for donoautoaddcolontolabels** ($options['forms'][$form_id]['donotautoaddcolontolabels'], 846)

[changes-fixes_sf_wp-to-lead_84.zip](https://github.com/BrilliantPlugins/salesforce-wordpress-to-lead/files/1674171/changes-fixes_sf_wp-to-lead_84.zip)


Hope it helps.

**Comment by nciske** [comment]
A few things to note:

1. That's just a notice, it doesn't affect functionality at all.
1. You should have error displayed _disabled_ on a production server.
1. This will be addressed in a future update.

**Comment by Lynda1952** [comment]
Thank you, GrimGramS, I will work with these tomorrow or Wednesday and let you know how it worked. nciske, I'm sorry, but I don't know how too disable error displayed, and not sure what you mean by "production server." Like I said - newbie. *soft smile*
