### ISSUE TITLE
checkbox option not working???

### ISSUE THREAD

**Issue by sfdc2019** [BrilliantPlugins/salesforce-wordpress-to-lead#94]
custom SFDC checkbox lead field being used:

based on article notes I've read I've:
(1) left value and options blank (but then the form starts with everything checked and if I check it on the form it still goes in blank to SFDC)
(2) added 0 to value, which leave the form checkbox unchecked (but then I check the form and when i submit to SFDC, the value goes in as unchecked into SFDC)

any thoughts.  This process is not very intuitive and there seems to be a bug present in your code.

Thanks.

**Comment by nciske** [comment]
Checkboxes must have a value, that’s just basic rules of HTML. 

`1` generally works well with Salesforce.
