### ISSUE TITLE
Unable to set a form submission's Redirect URL to open in a new tab

### ISSUE THREAD

**Issue by ibotta-charlotte** [BrilliantPlugins/salesforce-wordpress-to-lead#95]
Hi there, 

The plugin is fantastic and is working well with my company's website build. The only roadblock I've run into is that I can't force a form submission to open a redirect URL in a new tab rather than staying within the same tab and directing the lead away from our site. This would normally be accomplished with simple target="_blank" coding within the <form> tag but I have tried that by adding a hidden HTML field to the form and it does not work. 

Is this on your roadmap to update within the settings for each respective form (similar to how you can designate individual form's Captcha preferences and such)? 

Thank you,
Charlotte

**Comment by nciske** [comment]
Thanks, glad it's working well for you.

You could accomplish this by filtering the form HTML via the `salesforce_w2l_form_html` hook before output to add the `target="_blank"` attribute via search/replace function. 

I'm not sure if a plugin setting will ever materialize as this is not a common use case, and is iffy UX wise... in my experience. I could make it a simpler filter to implement, but development on this project is a bit in limbo at the moment. 

We'll be pushing an invite to a survey soon to have the userbase help determine the future of this plugin. Based on the outcome of that, this may or may not appear in a future release.
