### ISSUE TITLE
Leads coming in corrupt

### ISSUE THREAD

**Issue by jacaberry1** [BrilliantPlugins/salesforce-wordpress-to-lead#98]
When users are filling out our Demo Request form, the fields they fill out are being sent to us with corrupt text. We have pretty simple fields such as first name, last name, company and phone number. When I test myself if works, but for external this is not the case. All data is jumbled except for the email address. 

See example below. Has any experienced this or know how to fix?
Thanks!

First Name: aqogwJLjt
Last Name: ajJLoNpkBwMr
Company: mtjFyWcsOY
Company Size: 501-1,000
Number: eszYGafDEXbrIjOc
Keep me updated on news from Butterfly: ighWNdFM

**Comment by nciske** [comment]
There's nothing in the plugin that would cause this. I suspect the issue is another plugin on your website.
